version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: devtrack_db
    environment:
      POSTGRES_USER: devtrack_user
      POSTGRES_PASSWORD: devtrack_pass
      POSTGRES_DB: devtrack
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: